<?php

/**
 * @file
 * Js_confirm.module
 * Adds a simple Javascript confirmation to a node
 * add page. This could be extended to be used on
 * webform pages, or any page for that matter.
 * An Administrative page could also be created that
 * would allow you to specify multiple pages to run
 * code on. This just provides the simple example.
 */

/**
 * Implements hook_init().
 */
function js_confirm_init() {
  if (current_path() == 'node/add/article') {
    drupal_add_js("jQuery(document).ready(function () {
      jQuery(window).bind('beforeunload', function () {
       return 'You are currently creating an article, are you sure you want to leave? Any unsaved changes will be lost';
      });
    });", 'inline');
  }
}
