<?php


/**
 * Implements hook_permission()
 */
function myblock_permission()
{
  return array(
    'access mypage' => array(
      'title' => t('Access My page'),
      'description' => t('Access My page on my site.'),
    ),
  );
}

/**
 * Implements hook_menu()
 */
function myblock_menu()
{
  $items['mypage'] = array(
    'title' => 'My page',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'myblock_mypage',
    'access arguments' => array('access mypage'),
  );
  return $items;
}

/**
 * My callback function
 */
function myblock_mypage(){
  return "<strong>This is a test</strong>";
}

/**
 * Implements hook_block_info()
 */

function myblock_block_info() {

  $blocks['myblock'] = array(
    'info' => t('My magical block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */

function myblock_block_view($delta = '') {

  $block = array();
  switch ($delta) {
    case 'myblock':
      $block['subject'] = t('This is my magical block 👻');
      $block['content'] = "test";
      break;
  }
  return $block;
}
