<?php

/**
 * Implements hook_menu().
 */
function render_array_menu() {
  $items['page-html'] = array(
    'title' => 'My page with HTML style function',
    'page callback' => 'render_array_html_page',
    'access callback' => TRUE,
  );
  $items['page-renderable'] = array(
    'title' => 'My page with render array function',
    'page callback' => 'render_array_renderable_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implement hook_theme().
 */
function render_array_theme($existing, $type, $theme, $path) {
  return array(
    'render_array_function' => array(
      'variables' => array(
        'text_one' => NULL,
        'text_two' => NULL,
      ),
    ),
    'render_array_template' => array(
      'variables' => array(
        'text_one' => NULL,
        'text_two' => NULL,
      ),
      'template' => 'render_array_template',
    ),
  );
}

/**
 * Callback function using HTML output.
 */
function render_array_html_page() {
  $text_one = "This is text one";
  return theme('render_array_function', array('text_one' => $text_one, 'text_two' => 'Text Two!'));
}

/**
 * Callback function using renderable array.
 */
function render_array_renderable_page() {
  $text_one = "This is text one";
  $output = array(
    '#theme' => 'render_array_template',
    '#type' => 'markup',
    '#text_one' => $text_one,
    '#text_two' => 'Text Two',
  );
  return $output;
}

/**
 * Theme function example.
 */
function theme_render_array_function($variables) {
  $output = "<h2>" . $variables['text_one'] . "</h2>";
  $output .= "<p>" . $variables['text_two'] . "</p>";
  return $output;
}
